name: "datanode01"
token: "abc"

ip: "0.0.0.0"
port: 20001

index_path: "efs_index"
log_path: "efs_logs"
root_path: "efs_root"

disk_size: 1024

namenode_addr: "192.168.0.179"
namenode_port: 20000

paths: ["/zxt", "/root"]

# ["path,uid,gid"]
# ["/zxt,2,2"]
init_paths: ["/,1,1,40755", "/root,1,1,40700", "/zxt,2,2,40700"]
